version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      angular-core:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "build(deps): "
    open-pull-requests-limit: 10
